import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Flex } from "@chakra-ui/react";
import Header from "./components/header";
import { articlesPath } from "./constants";
import { getSubFoldersName } from "./lib/directoryUtils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "qQsss777 blog",
  description: "Generated by create next app - Juste pour apprendre",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const folders = await getSubFoldersName(process.cwd() + articlesPath);
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <Flex direction="column" minHeight="100vh">
            <Header rootPath="/" title="qQsss777 blog" articles={folders} />
            {children}
          </Flex>
        </Provider>
      </body>
    </html>
  );
}
